### ISSUE TITLE
torscraper/middlewares.py : raise ProgrammingError(e)

### ISSUE THREAD

**Issue by CorraMatte** [GoSecure/freshonions-torscraper#12]
Hi guys,
I follow your guide in order to install everything and actually it works great until the scripts/harverst.sh.

As soon I run the scraper, I get this error:
  `   except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON))\n  AND 'description_json_at' = '1970-01-01 01:00:00'' at line 31")`

Referred to:
`File "/root/freshonion/torscraper/middlewares.py", line 192, in <genexpr>                               
    return (_set_range(r) for r in result or ())`

I'm using the version 0.7.3 of pony, and version 10.1.34 of MariaDB.
The platform is based on Ubuntu Bionic 18.04.

What could be the solution to this problem?

**Comment by jeffwcollins** [comment]
Do you see it harvesting any data before the error?

**Comment by CorraMatte** [comment]
It actually collects the data, despite the error is present while the `harverst.sh` is running.
However I was wondering if that error could compromise the normal and correct behavior of the scraper in some way. And if it does, which are the correct version of the software to install.

**Comment by jeffwcollins** [comment]
I use a separate (external) mariadb server, running the same version as you, but my pony and the rest of the python modules are quite old (I haven’t updated since initially installing), so I can not confirm whether those are causing you issues.

Are you seeing data being populated in your database?

**Comment by CorraMatte** [comment]
I'm sure that the "domain" table is populated and also the web page is actually working!
Which pony module are you using by the way? I could try to use the same version to test if it is the problem.

**Comment by obilodeau** [comment]
@CorraMatte, can you enable the [MariaDB query log](https://mariadb.com/kb/en/library/general-query-log/), reproduce the issue and post the full stacktrace (not just one line) and also include the relevant SQL query (from the query log)?

Thanks

**Comment by jeffwcollins** [comment]
I’ve got:
Pony 0.7.6
Scrapy 1.5.1

**Comment by CorraMatte** [comment]
@jeffwcollins with your package versions I still have the problem

@obilodeau this is the full Python stacktrace
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)  
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/root/freshonion/torscraper/middlewares.py", line 192, in <genexpr>
    return (_set_range(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 606, in new_gen_func
    output = wrapped_interact(iterator)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 592, in wrapped_interact
    rollback_and_reraise(sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 370, in rollback_and_reraise
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 581, in wrapped_interact
    output = interact(iterator, input, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 554, in interact
    return next(iterator) if input is None else iterator.send(input)
  File "/root/freshonion/torscraper/spiders/tor_scrapy.py", line 2263, in parse
    commit()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 381, in commit
    rollback_and_reraise(sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 370, in rollback_and_reraise
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 379, in commit
    cache.flush()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1883, in flush
    if obj is not None: obj._save_()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 5358, in _save_
    elif status == 'modified': obj._save_updated_()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 5267, in _save_updated_
    cursor = database._exec_sql(sql, arguments, start_transaction=True)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 941, in _exec_sql
    connection = cache.reconnect(e)
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 1771, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 939, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<auto generated wrapper of execute() function>", line 2, in execute
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/dbapiprovider.py", line 56, in wrap_dbapi_exceptions
    except dbapi_module.ProgrammingError as e: raise ProgrammingError(e)
ProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use
near 'JSON))\n  AND 'description_json_at' = '1970-01-01 01:00:00'' at line 31")

This is the MariaDB log:
190207 10:19:11     6 Query     SELECT 'id', 'host', 'port', 'ssl', 'is_up', 'title', 'server', 'powered_by', 'is_crap', 'is_fake', 'is_genuine', 'is_subdomai
n', 'is_banned', 'manual_genuine', 'useful_404', 'useful_404_php', 'useful_404_dir', 'ban_exempt', 'language', 'created_at', 'visited_at', 'last_alive', 'clone_group', 'new_clone_group', 'next_scheduled_check', 'whatweb_at', 'dead_in_a_row', 'ssh_fingerprint', 'portscanned_at', 'path_scanned_at', 'useful_404_scanned_at', 'description_json', 'description_json_at'                                                                                                              FROM 'domain'                                                                                                                                                 WHERE 'host' = 'grams56vxvk4wtno.onion'
  AND 'port' = 80
  AND 'ssl' = 0
LIMIT 2
                    6 Query     COMMIT
                    6 Query     ROLLBACK
190207 10:19:12     6 Query     SELECT 'id', 'host', 'port', 'ssl', 'is_up', 'title', 'server', 'powered_by', 'is_crap', 'is_fake', 'is_genuine', 'is_subdomai
n', 'is_banned', 'manual_genuine', 'useful_404', 'useful_404_php', 'useful_404_dir', 'ban_exempt', 'language', 'created_at', 'visited_at', 'last_alive', 'clone_group', 'new_clone_group', 'next_scheduled_check', 'whatweb_at', 'dead_in_a_row', 'ssh_fingerprint', 'portscanned_at', 'path_scanned_at', 'useful_404_scanned_at', 'description_json', 'description_json_at'                                                                                                              FROM 'domain'                                                                                                                                                 WHERE 'host' = 'q3f47rcmwixmn5kx.onion'
  AND 'port' = 80
  AND 'ssl' = 0
LIMIT 2
                    6 Query     COMMIT
                    6 Query     ROLLBACK
190207 10:19:15     6 Query     SELECT 'id', 'host', 'port', 'ssl', 'is_up', 'title', 'server', 'powered_by', 'is_crap', 'is_fake', 'is_genuine', 'is_subdomai
n', 'is_banned', 'manual_genuine', 'useful_404', 'useful_404_php', 'useful_404_dir', 'ban_exempt', 'language', 'created_at', 'visited_at', 'last_alive', 'clone_group', 'new_clone_group', 'next_scheduled_check', 'whatweb_at', 'dead_in_a_row', 'ssh_fingerprint', 'portscanned_at', 'path_scanned_at', 'useful_404_scanned_at', 'description_json', 'description_json_at'                                                                                                              FROM 'domain'                                                                                                                                                 WHERE 'host' = '333agavwxzjsqgjd.onion'
  AND 'port' = 80
  AND 'ssl' = 0
LIMIT 2
                    6 Query     COMMIT
                    6 Query     ROLLBACK
190207 10:19:16     6 Query     SELECT 'id', 'host', 'port', 'ssl', 'is_up', 'title', 'server', 'powered_by', 'is_crap', 'is_fake', 'is_genuine', 'is_subdomai
n', 'is_banned', 'manual_genuine', 'useful_404', 'useful_404_php', 'useful_404_dir', 'ban_exempt', 'language', 'created_at', 'visited_at', 'last_alive', 'clone_group', 'new_clone_group', 'next_scheduled_check', 'whatweb_at', 'dead_in_a_row', 'ssh_fingerprint', 'portscanned_at', 'path_scanned_at', 'useful_404_scanned_at', 'description_json', 'description_json_at'                                                                                                              FROM 'domain'                                                                                                                                                 WHERE 'host' = 'un4sduyebvk4xr4w.onion'
  AND 'port' = 80
  AND 'ssl' = 0
LIMIT 2
                    6 Query     COMMIT
                    6 Query     ROLLBACK

**Comment by obilodeau** [comment]
Here is the result of my little bug hunting:

TorScraper uses JSON types for some of the data, [like here](https://github.com/GoSecure/freshonions-torscraper/blob/master/lib/tor_db/models/domain.py#L54) and [here](https://github.com/GoSecure/freshonions-torscraper/blob/master/lib/tor_db/models/search_log.py#L11).

Here is [pony's support table](https://docs.ponyorm.org/json.html#json-support-in-databases) for databases regarding the JSON type. MySQL is supported, MariaDB not explicitly supported but since it's a MySQL compatible fork it should work.

However, MariaDB only added support for the JSON keyword [in version 10.2](https://mariadb.com/kb/en/library/json-data-type/#differences-between-mysql-json-strings-and-mariadb-json-strings).

18.04 ships with [an older MariaDB](https://packages.ubuntu.com/bionic/mariadb-server-10.1).

So, upgrading MariaDB to 10.2 should fix that problem.

That said, our "production" instance of this project runs on MariaDB 10.0.x. So two possibilities here:

a) We had those errors and everything works fine anyways, meaning we don't have the website description json or the search log context json but we can live w/o it

b) We run an older Pony (0.7.3) which would handle JSON differently. MariaDB column type is `varchar(10240)` and I think pony avoids using the JSON keyword. Newer versions of pony might use that keyword.

Up to you to decide how you are going to handle this. Let us know what you did so we can act on the ticket accordingly.

Cheers!

**Comment by CorraMatte** [comment]
Thanks @obilodeau!
I chose to downgrade the python pony package, and now it works fine!

I consider this Issue closed.
